trigger:
- none

pool:
  name: default

variables:
 - group: packer-terraform-image-build-variables

steps:

- task: PowerShell@2
  inputs:
    azureSubscription: 'AkManagedIdentity'
    scriptType: 'powershell'
    scriptLocation: 'inlineScript'
    inlineScript: |
        # Navigate to the directory where your Terraform files are located
        Set-Location "$(Build.SourcesDirectory)/root"

 
        Write-Output "Logging in using Managed Identity..."
        az login --identity -u /subscriptions/761cc7e6-a477-494a-99ef-a5d6aa0fde41/resourcegroups/kun/providers/Microsoft.ManagedIdentity/userAssignedIdentities/AkManagedIdentity

        Write-Output "Showing account details..."
        az account show

        Write-Output "Terraform version:"
        terraform version

        Write-Output "Running terraform init..."
        terraform init

        Write-Output "Running terraform plan..."
        terraform plan

        Write-Output "Applying terraform..."
        terraform apply -auto-approve
     
     
  displayName: 'Install and Run terraform'
  env:
    TF_VAR_winrm_password: $(WINRM_PASSWORD)
    TF_VAR_domain_password: $(DOMAIN_PASSWORD)
